apiVersion: v1
kind: Pod
metadata:
  name: apparmor-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/example-container: localhost/k8s-apparmor-profile
spec:
  containers:
    - name: example-container
      image: busybox
